#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Loyung.DBModels
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Loyung")]
	public partial class LoyungDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    partial void InsertSYSDA(SYSDA instance);
    partial void UpdateSYSDA(SYSDA instance);
    partial void DeleteSYSDA(SYSDA instance);
    partial void InsertUSEUB(USEUB instance);
    partial void UpdateUSEUB(USEUB instance);
    partial void DeleteUSEUB(USEUB instance);
    partial void InsertSYSDB(SYSDB instance);
    partial void UpdateSYSDB(SYSDB instance);
    partial void DeleteSYSDB(SYSDB instance);
    partial void InsertSYSLA(SYSLA instance);
    partial void UpdateSYSLA(SYSLA instance);
    partial void DeleteSYSLA(SYSLA instance);
    partial void InsertSYSMA(SYSMA instance);
    partial void UpdateSYSMA(SYSMA instance);
    partial void DeleteSYSMA(SYSMA instance);
    partial void InsertSYSMB(SYSMB instance);
    partial void UpdateSYSMB(SYSMB instance);
    partial void DeleteSYSMB(SYSMB instance);
    partial void InsertSYSTA(SYSTA instance);
    partial void UpdateSYSTA(SYSTA instance);
    partial void DeleteSYSTA(SYSTA instance);
    partial void InsertSYSTB(SYSTB instance);
    partial void UpdateSYSTB(SYSTB instance);
    partial void DeleteSYSTB(SYSTB instance);
    partial void InsertUSERA(USERA instance);
    partial void UpdateUSERA(USERA instance);
    partial void DeleteUSERA(USERA instance);
    partial void InsertUSERB(USERB instance);
    partial void UpdateUSERB(USERB instance);
    partial void DeleteUSERB(USERB instance);
    partial void InsertUSERC(USERC instance);
    partial void UpdateUSERC(USERC instance);
    partial void DeleteUSERC(USERC instance);
    partial void InsertUSEUA(USEUA instance);
    partial void UpdateUSEUA(USEUA instance);
    partial void DeleteUSEUA(USEUA instance);
    #endregion
		
		public LoyungDBDataContext() : 
				base(global::Loyung.DBModels.Properties.Settings.Default.LoyungConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public LoyungDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LoyungDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LoyungDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LoyungDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<SYSDA> SYSDA
		{
			get
			{
				return this.GetTable<SYSDA>();
			}
		}
		
		public System.Data.Linq.Table<USEUB> USEUB
		{
			get
			{
				return this.GetTable<USEUB>();
			}
		}
		
		public System.Data.Linq.Table<SYSDB> SYSDB
		{
			get
			{
				return this.GetTable<SYSDB>();
			}
		}
		
		public System.Data.Linq.Table<SYSLA> SYSLA
		{
			get
			{
				return this.GetTable<SYSLA>();
			}
		}
		
		public System.Data.Linq.Table<SYSMA> SYSMA
		{
			get
			{
				return this.GetTable<SYSMA>();
			}
		}
		
		public System.Data.Linq.Table<SYSMB> SYSMB
		{
			get
			{
				return this.GetTable<SYSMB>();
			}
		}
		
		public System.Data.Linq.Table<SYSTA> SYSTA
		{
			get
			{
				return this.GetTable<SYSTA>();
			}
		}
		
		public System.Data.Linq.Table<SYSTB> SYSTB
		{
			get
			{
				return this.GetTable<SYSTB>();
			}
		}
		
		public System.Data.Linq.Table<USERA> USERA
		{
			get
			{
				return this.GetTable<USERA>();
			}
		}
		
		public System.Data.Linq.Table<USERB> USERB
		{
			get
			{
				return this.GetTable<USERB>();
			}
		}
		
		public System.Data.Linq.Table<USERC> USERC
		{
			get
			{
				return this.GetTable<USERC>();
			}
		}
		
		public System.Data.Linq.Table<USEUA> USEUA
		{
			get
			{
				return this.GetTable<USEUA>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SYSDA")]
	public partial class SYSDA : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _DA001;
		
		private string _DA002;
		
		private string _DA003;
		
		private EntitySet<SYSDB> _SYSDB;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnDA001Changing(string value);
    partial void OnDA001Changed();
    partial void OnDA002Changing(string value);
    partial void OnDA002Changed();
    partial void OnDA003Changing(string value);
    partial void OnDA003Changed();
    #endregion
		
		public SYSDA()
		{
			this._SYSDB = new EntitySet<SYSDB>(new Action<SYSDB>(this.attach_SYSDB), new Action<SYSDB>(this.detach_SYSDB));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DA001", DbType="VarChar(100)")]
		public string DA001
		{
			get
			{
				return this._DA001;
			}
			set
			{
				if ((this._DA001 != value))
				{
					this.OnDA001Changing(value);
					this.SendPropertyChanging();
					this._DA001 = value;
					this.SendPropertyChanged("DA001");
					this.OnDA001Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DA002", DbType="VarChar(50)")]
		public string DA002
		{
			get
			{
				return this._DA002;
			}
			set
			{
				if ((this._DA002 != value))
				{
					this.OnDA002Changing(value);
					this.SendPropertyChanging();
					this._DA002 = value;
					this.SendPropertyChanged("DA002");
					this.OnDA002Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DA003", DbType="VarChar(200)")]
		public string DA003
		{
			get
			{
				return this._DA003;
			}
			set
			{
				if ((this._DA003 != value))
				{
					this.OnDA003Changing(value);
					this.SendPropertyChanging();
					this._DA003 = value;
					this.SendPropertyChanged("DA003");
					this.OnDA003Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SYSDA_SYSDB", Storage="_SYSDB", ThisKey="ID", OtherKey="DB001")]
		public EntitySet<SYSDB> SYSDB
		{
			get
			{
				return this._SYSDB;
			}
			set
			{
				this._SYSDB.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_SYSDB(SYSDB entity)
		{
			this.SendPropertyChanging();
			entity.SYSDA = this;
		}
		
		private void detach_SYSDB(SYSDB entity)
		{
			this.SendPropertyChanging();
			entity.SYSDA = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.USEUB")]
	public partial class USEUB : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _ID;
		
		private System.Nullable<long> _UB001;
		
		private string _UB002;
		
		private string _UB003;
		
		private EntityRef<USEUA> _USEUA;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(long value);
    partial void OnIDChanged();
    partial void OnUB001Changing(System.Nullable<long> value);
    partial void OnUB001Changed();
    partial void OnUB002Changing(string value);
    partial void OnUB002Changed();
    partial void OnUB003Changing(string value);
    partial void OnUB003Changed();
    #endregion
		
		public USEUB()
		{
			this._USEUA = default(EntityRef<USEUA>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UB001", DbType="BigInt")]
		public System.Nullable<long> UB001
		{
			get
			{
				return this._UB001;
			}
			set
			{
				if ((this._UB001 != value))
				{
					if (this._USEUA.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnUB001Changing(value);
					this.SendPropertyChanging();
					this._UB001 = value;
					this.SendPropertyChanged("UB001");
					this.OnUB001Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UB002", DbType="VarChar(50)")]
		public string UB002
		{
			get
			{
				return this._UB002;
			}
			set
			{
				if ((this._UB002 != value))
				{
					this.OnUB002Changing(value);
					this.SendPropertyChanging();
					this._UB002 = value;
					this.SendPropertyChanged("UB002");
					this.OnUB002Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UB003", DbType="VarChar(200)")]
		public string UB003
		{
			get
			{
				return this._UB003;
			}
			set
			{
				if ((this._UB003 != value))
				{
					this.OnUB003Changing(value);
					this.SendPropertyChanging();
					this._UB003 = value;
					this.SendPropertyChanged("UB003");
					this.OnUB003Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="USEUA_USEUB", Storage="_USEUA", ThisKey="UB001", OtherKey="ID", IsForeignKey=true)]
		public USEUA USEUA
		{
			get
			{
				return this._USEUA.Entity;
			}
			set
			{
				USEUA previousValue = this._USEUA.Entity;
				if (((previousValue != value) 
							|| (this._USEUA.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._USEUA.Entity = null;
						previousValue.USEUB.Remove(this);
					}
					this._USEUA.Entity = value;
					if ((value != null))
					{
						value.USEUB.Add(this);
						this._UB001 = value.ID;
					}
					else
					{
						this._UB001 = default(Nullable<long>);
					}
					this.SendPropertyChanged("USEUA");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SYSDB")]
	public partial class SYSDB : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.Nullable<int> _DB001;
		
		private string _DB002;
		
		private string _DB003;
		
		private string _DB004;
		
		private EntityRef<SYSDA> _SYSDA;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnDB001Changing(System.Nullable<int> value);
    partial void OnDB001Changed();
    partial void OnDB002Changing(string value);
    partial void OnDB002Changed();
    partial void OnDB003Changing(string value);
    partial void OnDB003Changed();
    partial void OnDB004Changing(string value);
    partial void OnDB004Changed();
    #endregion
		
		public SYSDB()
		{
			this._SYSDA = default(EntityRef<SYSDA>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DB001", DbType="Int")]
		public System.Nullable<int> DB001
		{
			get
			{
				return this._DB001;
			}
			set
			{
				if ((this._DB001 != value))
				{
					if (this._SYSDA.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnDB001Changing(value);
					this.SendPropertyChanging();
					this._DB001 = value;
					this.SendPropertyChanged("DB001");
					this.OnDB001Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DB002", DbType="VarChar(50)")]
		public string DB002
		{
			get
			{
				return this._DB002;
			}
			set
			{
				if ((this._DB002 != value))
				{
					this.OnDB002Changing(value);
					this.SendPropertyChanging();
					this._DB002 = value;
					this.SendPropertyChanged("DB002");
					this.OnDB002Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DB003", DbType="VarChar(50)")]
		public string DB003
		{
			get
			{
				return this._DB003;
			}
			set
			{
				if ((this._DB003 != value))
				{
					this.OnDB003Changing(value);
					this.SendPropertyChanging();
					this._DB003 = value;
					this.SendPropertyChanged("DB003");
					this.OnDB003Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DB004", DbType="VarChar(200)")]
		public string DB004
		{
			get
			{
				return this._DB004;
			}
			set
			{
				if ((this._DB004 != value))
				{
					this.OnDB004Changing(value);
					this.SendPropertyChanging();
					this._DB004 = value;
					this.SendPropertyChanged("DB004");
					this.OnDB004Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SYSDA_SYSDB", Storage="_SYSDA", ThisKey="DB001", OtherKey="ID", IsForeignKey=true)]
		public SYSDA SYSDA
		{
			get
			{
				return this._SYSDA.Entity;
			}
			set
			{
				SYSDA previousValue = this._SYSDA.Entity;
				if (((previousValue != value) 
							|| (this._SYSDA.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._SYSDA.Entity = null;
						previousValue.SYSDB.Remove(this);
					}
					this._SYSDA.Entity = value;
					if ((value != null))
					{
						value.SYSDB.Add(this);
						this._DB001 = value.ID;
					}
					else
					{
						this._DB001 = default(Nullable<int>);
					}
					this.SendPropertyChanged("SYSDA");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SYSLA")]
	public partial class SYSLA : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _ID;
		
		private string _LA001;
		
		private string _LA002;
		
		private string _LA003;
		
		private System.Nullable<long> _LA004;
		
		private System.Nullable<System.DateTime> _LA005;
		
		private EntityRef<USEUA> _USEUA;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(long value);
    partial void OnIDChanged();
    partial void OnLA001Changing(string value);
    partial void OnLA001Changed();
    partial void OnLA002Changing(string value);
    partial void OnLA002Changed();
    partial void OnLA003Changing(string value);
    partial void OnLA003Changed();
    partial void OnLA004Changing(System.Nullable<long> value);
    partial void OnLA004Changed();
    partial void OnLA005Changing(System.Nullable<System.DateTime> value);
    partial void OnLA005Changed();
    #endregion
		
		public SYSLA()
		{
			this._USEUA = default(EntityRef<USEUA>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LA001", DbType="VarChar(1000)")]
		public string LA001
		{
			get
			{
				return this._LA001;
			}
			set
			{
				if ((this._LA001 != value))
				{
					this.OnLA001Changing(value);
					this.SendPropertyChanging();
					this._LA001 = value;
					this.SendPropertyChanged("LA001");
					this.OnLA001Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LA002", DbType="VarChar(200)")]
		public string LA002
		{
			get
			{
				return this._LA002;
			}
			set
			{
				if ((this._LA002 != value))
				{
					this.OnLA002Changing(value);
					this.SendPropertyChanging();
					this._LA002 = value;
					this.SendPropertyChanged("LA002");
					this.OnLA002Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LA003", DbType="VarChar(200)")]
		public string LA003
		{
			get
			{
				return this._LA003;
			}
			set
			{
				if ((this._LA003 != value))
				{
					this.OnLA003Changing(value);
					this.SendPropertyChanging();
					this._LA003 = value;
					this.SendPropertyChanged("LA003");
					this.OnLA003Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LA004", DbType="BigInt")]
		public System.Nullable<long> LA004
		{
			get
			{
				return this._LA004;
			}
			set
			{
				if ((this._LA004 != value))
				{
					if (this._USEUA.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnLA004Changing(value);
					this.SendPropertyChanging();
					this._LA004 = value;
					this.SendPropertyChanged("LA004");
					this.OnLA004Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LA005", DbType="DateTime")]
		public System.Nullable<System.DateTime> LA005
		{
			get
			{
				return this._LA005;
			}
			set
			{
				if ((this._LA005 != value))
				{
					this.OnLA005Changing(value);
					this.SendPropertyChanging();
					this._LA005 = value;
					this.SendPropertyChanged("LA005");
					this.OnLA005Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="USEUA_SYSLA", Storage="_USEUA", ThisKey="LA004", OtherKey="ID", IsForeignKey=true)]
		public USEUA USEUA
		{
			get
			{
				return this._USEUA.Entity;
			}
			set
			{
				USEUA previousValue = this._USEUA.Entity;
				if (((previousValue != value) 
							|| (this._USEUA.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._USEUA.Entity = null;
						previousValue.SYSLA.Remove(this);
					}
					this._USEUA.Entity = value;
					if ((value != null))
					{
						value.SYSLA.Add(this);
						this._LA004 = value.ID;
					}
					else
					{
						this._LA004 = default(Nullable<long>);
					}
					this.SendPropertyChanged("USEUA");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SYSMA")]
	public partial class SYSMA : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _MA001;
		
		private string _MA002;
		
		private string _MA003;
		
		private string _MA004;
		
		private System.Nullable<int> _MA005;
		
		private string _MA006;
		
		private System.Nullable<bool> _MA007;
		
		private EntitySet<SYSMB> _SYSMB;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnMA001Changing(string value);
    partial void OnMA001Changed();
    partial void OnMA002Changing(string value);
    partial void OnMA002Changed();
    partial void OnMA003Changing(string value);
    partial void OnMA003Changed();
    partial void OnMA004Changing(string value);
    partial void OnMA004Changed();
    partial void OnMA005Changing(System.Nullable<int> value);
    partial void OnMA005Changed();
    partial void OnMA006Changing(string value);
    partial void OnMA006Changed();
    partial void OnMA007Changing(System.Nullable<bool> value);
    partial void OnMA007Changed();
    #endregion
		
		public SYSMA()
		{
			this._SYSMB = new EntitySet<SYSMB>(new Action<SYSMB>(this.attach_SYSMB), new Action<SYSMB>(this.detach_SYSMB));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MA001", DbType="VarChar(50)")]
		public string MA001
		{
			get
			{
				return this._MA001;
			}
			set
			{
				if ((this._MA001 != value))
				{
					this.OnMA001Changing(value);
					this.SendPropertyChanging();
					this._MA001 = value;
					this.SendPropertyChanged("MA001");
					this.OnMA001Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MA002", DbType="VarChar(50)")]
		public string MA002
		{
			get
			{
				return this._MA002;
			}
			set
			{
				if ((this._MA002 != value))
				{
					this.OnMA002Changing(value);
					this.SendPropertyChanging();
					this._MA002 = value;
					this.SendPropertyChanged("MA002");
					this.OnMA002Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MA003", DbType="VarChar(200)")]
		public string MA003
		{
			get
			{
				return this._MA003;
			}
			set
			{
				if ((this._MA003 != value))
				{
					this.OnMA003Changing(value);
					this.SendPropertyChanging();
					this._MA003 = value;
					this.SendPropertyChanged("MA003");
					this.OnMA003Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MA004", DbType="VarChar(20)")]
		public string MA004
		{
			get
			{
				return this._MA004;
			}
			set
			{
				if ((this._MA004 != value))
				{
					this.OnMA004Changing(value);
					this.SendPropertyChanging();
					this._MA004 = value;
					this.SendPropertyChanged("MA004");
					this.OnMA004Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MA005", DbType="Int")]
		public System.Nullable<int> MA005
		{
			get
			{
				return this._MA005;
			}
			set
			{
				if ((this._MA005 != value))
				{
					this.OnMA005Changing(value);
					this.SendPropertyChanging();
					this._MA005 = value;
					this.SendPropertyChanged("MA005");
					this.OnMA005Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MA006", DbType="VarChar(200)")]
		public string MA006
		{
			get
			{
				return this._MA006;
			}
			set
			{
				if ((this._MA006 != value))
				{
					this.OnMA006Changing(value);
					this.SendPropertyChanging();
					this._MA006 = value;
					this.SendPropertyChanged("MA006");
					this.OnMA006Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MA007", DbType="Bit")]
		public System.Nullable<bool> MA007
		{
			get
			{
				return this._MA007;
			}
			set
			{
				if ((this._MA007 != value))
				{
					this.OnMA007Changing(value);
					this.SendPropertyChanging();
					this._MA007 = value;
					this.SendPropertyChanged("MA007");
					this.OnMA007Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SYSMA_SYSMB", Storage="_SYSMB", ThisKey="ID", OtherKey="MB001")]
		public EntitySet<SYSMB> SYSMB
		{
			get
			{
				return this._SYSMB;
			}
			set
			{
				this._SYSMB.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_SYSMB(SYSMB entity)
		{
			this.SendPropertyChanging();
			entity.SYSMA = this;
		}
		
		private void detach_SYSMB(SYSMB entity)
		{
			this.SendPropertyChanging();
			entity.SYSMA = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SYSMB")]
	public partial class SYSMB : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.Nullable<int> _MB001;
		
		private string _MB002;
		
		private string _MB003;
		
		private System.Nullable<bool> _MB004;
		
		private EntitySet<USERB> _USERB;
		
		private EntityRef<SYSMA> _SYSMA;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnMB001Changing(System.Nullable<int> value);
    partial void OnMB001Changed();
    partial void OnMB002Changing(string value);
    partial void OnMB002Changed();
    partial void OnMB003Changing(string value);
    partial void OnMB003Changed();
    partial void OnMB004Changing(System.Nullable<bool> value);
    partial void OnMB004Changed();
    #endregion
		
		public SYSMB()
		{
			this._USERB = new EntitySet<USERB>(new Action<USERB>(this.attach_USERB), new Action<USERB>(this.detach_USERB));
			this._SYSMA = default(EntityRef<SYSMA>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MB001", DbType="Int")]
		public System.Nullable<int> MB001
		{
			get
			{
				return this._MB001;
			}
			set
			{
				if ((this._MB001 != value))
				{
					if (this._SYSMA.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMB001Changing(value);
					this.SendPropertyChanging();
					this._MB001 = value;
					this.SendPropertyChanged("MB001");
					this.OnMB001Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MB002", DbType="VarChar(50)")]
		public string MB002
		{
			get
			{
				return this._MB002;
			}
			set
			{
				if ((this._MB002 != value))
				{
					this.OnMB002Changing(value);
					this.SendPropertyChanging();
					this._MB002 = value;
					this.SendPropertyChanged("MB002");
					this.OnMB002Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MB003", DbType="VarChar(50)")]
		public string MB003
		{
			get
			{
				return this._MB003;
			}
			set
			{
				if ((this._MB003 != value))
				{
					this.OnMB003Changing(value);
					this.SendPropertyChanging();
					this._MB003 = value;
					this.SendPropertyChanged("MB003");
					this.OnMB003Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MB004", DbType="Bit")]
		public System.Nullable<bool> MB004
		{
			get
			{
				return this._MB004;
			}
			set
			{
				if ((this._MB004 != value))
				{
					this.OnMB004Changing(value);
					this.SendPropertyChanging();
					this._MB004 = value;
					this.SendPropertyChanged("MB004");
					this.OnMB004Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SYSMB_USERB", Storage="_USERB", ThisKey="ID", OtherKey="RB002")]
		public EntitySet<USERB> USERB
		{
			get
			{
				return this._USERB;
			}
			set
			{
				this._USERB.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SYSMA_SYSMB", Storage="_SYSMA", ThisKey="MB001", OtherKey="ID", IsForeignKey=true)]
		public SYSMA SYSMA
		{
			get
			{
				return this._SYSMA.Entity;
			}
			set
			{
				SYSMA previousValue = this._SYSMA.Entity;
				if (((previousValue != value) 
							|| (this._SYSMA.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._SYSMA.Entity = null;
						previousValue.SYSMB.Remove(this);
					}
					this._SYSMA.Entity = value;
					if ((value != null))
					{
						value.SYSMB.Add(this);
						this._MB001 = value.ID;
					}
					else
					{
						this._MB001 = default(Nullable<int>);
					}
					this.SendPropertyChanged("SYSMA");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_USERB(USERB entity)
		{
			this.SendPropertyChanging();
			entity.SYSMB = this;
		}
		
		private void detach_USERB(USERB entity)
		{
			this.SendPropertyChanging();
			entity.SYSMB = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SYSTA")]
	public partial class SYSTA : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _TA001;
		
		private string _TA002;
		
		private System.Nullable<int> _TA003;
		
		private string _TA004;
		
		private EntitySet<SYSTB> _SYSTB;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnTA001Changing(string value);
    partial void OnTA001Changed();
    partial void OnTA002Changing(string value);
    partial void OnTA002Changed();
    partial void OnTA003Changing(System.Nullable<int> value);
    partial void OnTA003Changed();
    partial void OnTA004Changing(string value);
    partial void OnTA004Changed();
    #endregion
		
		public SYSTA()
		{
			this._SYSTB = new EntitySet<SYSTB>(new Action<SYSTB>(this.attach_SYSTB), new Action<SYSTB>(this.detach_SYSTB));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TA001", DbType="VarChar(50)")]
		public string TA001
		{
			get
			{
				return this._TA001;
			}
			set
			{
				if ((this._TA001 != value))
				{
					this.OnTA001Changing(value);
					this.SendPropertyChanging();
					this._TA001 = value;
					this.SendPropertyChanged("TA001");
					this.OnTA001Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TA002", DbType="VarChar(20)")]
		public string TA002
		{
			get
			{
				return this._TA002;
			}
			set
			{
				if ((this._TA002 != value))
				{
					this.OnTA002Changing(value);
					this.SendPropertyChanging();
					this._TA002 = value;
					this.SendPropertyChanged("TA002");
					this.OnTA002Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TA003", DbType="Int")]
		public System.Nullable<int> TA003
		{
			get
			{
				return this._TA003;
			}
			set
			{
				if ((this._TA003 != value))
				{
					this.OnTA003Changing(value);
					this.SendPropertyChanging();
					this._TA003 = value;
					this.SendPropertyChanged("TA003");
					this.OnTA003Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TA004", DbType="VarChar(200)")]
		public string TA004
		{
			get
			{
				return this._TA004;
			}
			set
			{
				if ((this._TA004 != value))
				{
					this.OnTA004Changing(value);
					this.SendPropertyChanging();
					this._TA004 = value;
					this.SendPropertyChanged("TA004");
					this.OnTA004Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SYSTA_SYSTB", Storage="_SYSTB", ThisKey="ID", OtherKey="TB002")]
		public EntitySet<SYSTB> SYSTB
		{
			get
			{
				return this._SYSTB;
			}
			set
			{
				this._SYSTB.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_SYSTB(SYSTB entity)
		{
			this.SendPropertyChanging();
			entity.SYSTA = this;
		}
		
		private void detach_SYSTB(SYSTB entity)
		{
			this.SendPropertyChanging();
			entity.SYSTA = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SYSTB")]
	public partial class SYSTB : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.Nullable<long> _TB001;
		
		private System.Nullable<int> _TB002;
		
		private EntityRef<SYSTA> _SYSTA;
		
		private EntityRef<USEUA> _USEUA;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnTB001Changing(System.Nullable<long> value);
    partial void OnTB001Changed();
    partial void OnTB002Changing(System.Nullable<int> value);
    partial void OnTB002Changed();
    #endregion
		
		public SYSTB()
		{
			this._SYSTA = default(EntityRef<SYSTA>);
			this._USEUA = default(EntityRef<USEUA>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TB001", DbType="BigInt")]
		public System.Nullable<long> TB001
		{
			get
			{
				return this._TB001;
			}
			set
			{
				if ((this._TB001 != value))
				{
					if (this._USEUA.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnTB001Changing(value);
					this.SendPropertyChanging();
					this._TB001 = value;
					this.SendPropertyChanged("TB001");
					this.OnTB001Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TB002", DbType="Int")]
		public System.Nullable<int> TB002
		{
			get
			{
				return this._TB002;
			}
			set
			{
				if ((this._TB002 != value))
				{
					if (this._SYSTA.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnTB002Changing(value);
					this.SendPropertyChanging();
					this._TB002 = value;
					this.SendPropertyChanged("TB002");
					this.OnTB002Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SYSTA_SYSTB", Storage="_SYSTA", ThisKey="TB002", OtherKey="ID", IsForeignKey=true)]
		public SYSTA SYSTA
		{
			get
			{
				return this._SYSTA.Entity;
			}
			set
			{
				SYSTA previousValue = this._SYSTA.Entity;
				if (((previousValue != value) 
							|| (this._SYSTA.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._SYSTA.Entity = null;
						previousValue.SYSTB.Remove(this);
					}
					this._SYSTA.Entity = value;
					if ((value != null))
					{
						value.SYSTB.Add(this);
						this._TB002 = value.ID;
					}
					else
					{
						this._TB002 = default(Nullable<int>);
					}
					this.SendPropertyChanged("SYSTA");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="USEUA_SYSTB", Storage="_USEUA", ThisKey="TB001", OtherKey="ID", IsForeignKey=true)]
		public USEUA USEUA
		{
			get
			{
				return this._USEUA.Entity;
			}
			set
			{
				USEUA previousValue = this._USEUA.Entity;
				if (((previousValue != value) 
							|| (this._USEUA.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._USEUA.Entity = null;
						previousValue.SYSTB.Remove(this);
					}
					this._USEUA.Entity = value;
					if ((value != null))
					{
						value.SYSTB.Add(this);
						this._TB001 = value.ID;
					}
					else
					{
						this._TB001 = default(Nullable<long>);
					}
					this.SendPropertyChanged("USEUA");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.USERA")]
	public partial class USERA : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _RA001;
		
		private string _RA002;
		
		private System.Nullable<bool> _RA003;
		
		private EntitySet<USERB> _USERB;
		
		private EntitySet<USERC> _USERC;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnRA001Changing(string value);
    partial void OnRA001Changed();
    partial void OnRA002Changing(string value);
    partial void OnRA002Changed();
    partial void OnRA003Changing(System.Nullable<bool> value);
    partial void OnRA003Changed();
    #endregion
		
		public USERA()
		{
			this._USERB = new EntitySet<USERB>(new Action<USERB>(this.attach_USERB), new Action<USERB>(this.detach_USERB));
			this._USERC = new EntitySet<USERC>(new Action<USERC>(this.attach_USERC), new Action<USERC>(this.detach_USERC));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RA001", DbType="VarChar(50)")]
		public string RA001
		{
			get
			{
				return this._RA001;
			}
			set
			{
				if ((this._RA001 != value))
				{
					this.OnRA001Changing(value);
					this.SendPropertyChanging();
					this._RA001 = value;
					this.SendPropertyChanged("RA001");
					this.OnRA001Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RA002", DbType="VarChar(500)")]
		public string RA002
		{
			get
			{
				return this._RA002;
			}
			set
			{
				if ((this._RA002 != value))
				{
					this.OnRA002Changing(value);
					this.SendPropertyChanging();
					this._RA002 = value;
					this.SendPropertyChanged("RA002");
					this.OnRA002Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RA003", DbType="Bit")]
		public System.Nullable<bool> RA003
		{
			get
			{
				return this._RA003;
			}
			set
			{
				if ((this._RA003 != value))
				{
					this.OnRA003Changing(value);
					this.SendPropertyChanging();
					this._RA003 = value;
					this.SendPropertyChanged("RA003");
					this.OnRA003Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="USERA_USERB", Storage="_USERB", ThisKey="ID", OtherKey="RB001")]
		public EntitySet<USERB> USERB
		{
			get
			{
				return this._USERB;
			}
			set
			{
				this._USERB.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="USERA_USERC", Storage="_USERC", ThisKey="ID", OtherKey="RC002")]
		public EntitySet<USERC> USERC
		{
			get
			{
				return this._USERC;
			}
			set
			{
				this._USERC.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_USERB(USERB entity)
		{
			this.SendPropertyChanging();
			entity.USERA = this;
		}
		
		private void detach_USERB(USERB entity)
		{
			this.SendPropertyChanging();
			entity.USERA = null;
		}
		
		private void attach_USERC(USERC entity)
		{
			this.SendPropertyChanging();
			entity.USERA = this;
		}
		
		private void detach_USERC(USERC entity)
		{
			this.SendPropertyChanging();
			entity.USERA = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.USERB")]
	public partial class USERB : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.Nullable<int> _RB001;
		
		private System.Nullable<int> _RB002;
		
		private EntityRef<USERA> _USERA;
		
		private EntityRef<SYSMB> _SYSMB;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnRB001Changing(System.Nullable<int> value);
    partial void OnRB001Changed();
    partial void OnRB002Changing(System.Nullable<int> value);
    partial void OnRB002Changed();
    #endregion
		
		public USERB()
		{
			this._USERA = default(EntityRef<USERA>);
			this._SYSMB = default(EntityRef<SYSMB>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RB001", DbType="Int")]
		public System.Nullable<int> RB001
		{
			get
			{
				return this._RB001;
			}
			set
			{
				if ((this._RB001 != value))
				{
					if (this._USERA.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnRB001Changing(value);
					this.SendPropertyChanging();
					this._RB001 = value;
					this.SendPropertyChanged("RB001");
					this.OnRB001Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RB002", DbType="Int")]
		public System.Nullable<int> RB002
		{
			get
			{
				return this._RB002;
			}
			set
			{
				if ((this._RB002 != value))
				{
					if (this._SYSMB.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnRB002Changing(value);
					this.SendPropertyChanging();
					this._RB002 = value;
					this.SendPropertyChanged("RB002");
					this.OnRB002Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="USERA_USERB", Storage="_USERA", ThisKey="RB001", OtherKey="ID", IsForeignKey=true)]
		public USERA USERA
		{
			get
			{
				return this._USERA.Entity;
			}
			set
			{
				USERA previousValue = this._USERA.Entity;
				if (((previousValue != value) 
							|| (this._USERA.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._USERA.Entity = null;
						previousValue.USERB.Remove(this);
					}
					this._USERA.Entity = value;
					if ((value != null))
					{
						value.USERB.Add(this);
						this._RB001 = value.ID;
					}
					else
					{
						this._RB001 = default(Nullable<int>);
					}
					this.SendPropertyChanged("USERA");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SYSMB_USERB", Storage="_SYSMB", ThisKey="RB002", OtherKey="ID", IsForeignKey=true)]
		public SYSMB SYSMB
		{
			get
			{
				return this._SYSMB.Entity;
			}
			set
			{
				SYSMB previousValue = this._SYSMB.Entity;
				if (((previousValue != value) 
							|| (this._SYSMB.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._SYSMB.Entity = null;
						previousValue.USERB.Remove(this);
					}
					this._SYSMB.Entity = value;
					if ((value != null))
					{
						value.USERB.Add(this);
						this._RB002 = value.ID;
					}
					else
					{
						this._RB002 = default(Nullable<int>);
					}
					this.SendPropertyChanged("SYSMB");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.USERC")]
	public partial class USERC : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.Nullable<long> _RC001;
		
		private System.Nullable<int> _RC002;
		
		private EntityRef<USERA> _USERA;
		
		private EntityRef<USEUA> _USEUA;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnRC001Changing(System.Nullable<long> value);
    partial void OnRC001Changed();
    partial void OnRC002Changing(System.Nullable<int> value);
    partial void OnRC002Changed();
    #endregion
		
		public USERC()
		{
			this._USERA = default(EntityRef<USERA>);
			this._USEUA = default(EntityRef<USEUA>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RC001", DbType="BigInt")]
		public System.Nullable<long> RC001
		{
			get
			{
				return this._RC001;
			}
			set
			{
				if ((this._RC001 != value))
				{
					if (this._USEUA.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnRC001Changing(value);
					this.SendPropertyChanging();
					this._RC001 = value;
					this.SendPropertyChanged("RC001");
					this.OnRC001Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RC002", DbType="Int")]
		public System.Nullable<int> RC002
		{
			get
			{
				return this._RC002;
			}
			set
			{
				if ((this._RC002 != value))
				{
					if (this._USERA.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnRC002Changing(value);
					this.SendPropertyChanging();
					this._RC002 = value;
					this.SendPropertyChanged("RC002");
					this.OnRC002Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="USERA_USERC", Storage="_USERA", ThisKey="RC002", OtherKey="ID", IsForeignKey=true)]
		public USERA USERA
		{
			get
			{
				return this._USERA.Entity;
			}
			set
			{
				USERA previousValue = this._USERA.Entity;
				if (((previousValue != value) 
							|| (this._USERA.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._USERA.Entity = null;
						previousValue.USERC.Remove(this);
					}
					this._USERA.Entity = value;
					if ((value != null))
					{
						value.USERC.Add(this);
						this._RC002 = value.ID;
					}
					else
					{
						this._RC002 = default(Nullable<int>);
					}
					this.SendPropertyChanged("USERA");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="USEUA_USERC", Storage="_USEUA", ThisKey="RC001", OtherKey="ID", IsForeignKey=true)]
		public USEUA USEUA
		{
			get
			{
				return this._USEUA.Entity;
			}
			set
			{
				USEUA previousValue = this._USEUA.Entity;
				if (((previousValue != value) 
							|| (this._USEUA.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._USEUA.Entity = null;
						previousValue.USERC.Remove(this);
					}
					this._USEUA.Entity = value;
					if ((value != null))
					{
						value.USERC.Add(this);
						this._RC001 = value.ID;
					}
					else
					{
						this._RC001 = default(Nullable<long>);
					}
					this.SendPropertyChanged("USEUA");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.USEUA")]
	public partial class USEUA : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _ID;
		
		private string _UA001;
		
		private string _UA002;
		
		private string _UA003;
		
		private string _UA004;
		
		private System.Nullable<System.DateTime> _UA005;
		
		private string _UA006;
		
		private string _UA007;
		
		private string _UA008;
		
		private string _UA009;
		
		private string _UA010;
		
		private System.Nullable<System.DateTime> _UA011;
		
		private System.Nullable<bool> _UA012;
		
		private System.Nullable<bool> _UA100;
		
		private string _UA101;
		
		private EntitySet<USEUB> _USEUB;
		
		private EntitySet<SYSLA> _SYSLA;
		
		private EntitySet<SYSTB> _SYSTB;
		
		private EntitySet<USERC> _USERC;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(long value);
    partial void OnIDChanged();
    partial void OnUA001Changing(string value);
    partial void OnUA001Changed();
    partial void OnUA002Changing(string value);
    partial void OnUA002Changed();
    partial void OnUA003Changing(string value);
    partial void OnUA003Changed();
    partial void OnUA004Changing(string value);
    partial void OnUA004Changed();
    partial void OnUA005Changing(System.Nullable<System.DateTime> value);
    partial void OnUA005Changed();
    partial void OnUA006Changing(string value);
    partial void OnUA006Changed();
    partial void OnUA007Changing(string value);
    partial void OnUA007Changed();
    partial void OnUA008Changing(string value);
    partial void OnUA008Changed();
    partial void OnUA009Changing(string value);
    partial void OnUA009Changed();
    partial void OnUA010Changing(string value);
    partial void OnUA010Changed();
    partial void OnUA011Changing(System.Nullable<System.DateTime> value);
    partial void OnUA011Changed();
    partial void OnUA012Changing(System.Nullable<bool> value);
    partial void OnUA012Changed();
    partial void OnUA100Changing(System.Nullable<bool> value);
    partial void OnUA100Changed();
    partial void OnUA101Changing(string value);
    partial void OnUA101Changed();
    #endregion
		
		public USEUA()
		{
			this._USEUB = new EntitySet<USEUB>(new Action<USEUB>(this.attach_USEUB), new Action<USEUB>(this.detach_USEUB));
			this._SYSLA = new EntitySet<SYSLA>(new Action<SYSLA>(this.attach_SYSLA), new Action<SYSLA>(this.detach_SYSLA));
			this._SYSTB = new EntitySet<SYSTB>(new Action<SYSTB>(this.attach_SYSTB), new Action<SYSTB>(this.detach_SYSTB));
			this._USERC = new EntitySet<USERC>(new Action<USERC>(this.attach_USERC), new Action<USERC>(this.detach_USERC));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UA001", DbType="VarChar(50)")]
		public string UA001
		{
			get
			{
				return this._UA001;
			}
			set
			{
				if ((this._UA001 != value))
				{
					this.OnUA001Changing(value);
					this.SendPropertyChanging();
					this._UA001 = value;
					this.SendPropertyChanged("UA001");
					this.OnUA001Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UA002", DbType="VarChar(50)")]
		public string UA002
		{
			get
			{
				return this._UA002;
			}
			set
			{
				if ((this._UA002 != value))
				{
					this.OnUA002Changing(value);
					this.SendPropertyChanging();
					this._UA002 = value;
					this.SendPropertyChanged("UA002");
					this.OnUA002Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UA003", DbType="VarChar(50)")]
		public string UA003
		{
			get
			{
				return this._UA003;
			}
			set
			{
				if ((this._UA003 != value))
				{
					this.OnUA003Changing(value);
					this.SendPropertyChanging();
					this._UA003 = value;
					this.SendPropertyChanged("UA003");
					this.OnUA003Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UA004", DbType="VarChar(2)")]
		public string UA004
		{
			get
			{
				return this._UA004;
			}
			set
			{
				if ((this._UA004 != value))
				{
					this.OnUA004Changing(value);
					this.SendPropertyChanging();
					this._UA004 = value;
					this.SendPropertyChanged("UA004");
					this.OnUA004Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UA005", DbType="DateTime")]
		public System.Nullable<System.DateTime> UA005
		{
			get
			{
				return this._UA005;
			}
			set
			{
				if ((this._UA005 != value))
				{
					this.OnUA005Changing(value);
					this.SendPropertyChanging();
					this._UA005 = value;
					this.SendPropertyChanged("UA005");
					this.OnUA005Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UA006", DbType="VarChar(50)")]
		public string UA006
		{
			get
			{
				return this._UA006;
			}
			set
			{
				if ((this._UA006 != value))
				{
					this.OnUA006Changing(value);
					this.SendPropertyChanging();
					this._UA006 = value;
					this.SendPropertyChanged("UA006");
					this.OnUA006Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UA007", DbType="VarChar(50)")]
		public string UA007
		{
			get
			{
				return this._UA007;
			}
			set
			{
				if ((this._UA007 != value))
				{
					this.OnUA007Changing(value);
					this.SendPropertyChanging();
					this._UA007 = value;
					this.SendPropertyChanged("UA007");
					this.OnUA007Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UA008", DbType="VarChar(50)")]
		public string UA008
		{
			get
			{
				return this._UA008;
			}
			set
			{
				if ((this._UA008 != value))
				{
					this.OnUA008Changing(value);
					this.SendPropertyChanging();
					this._UA008 = value;
					this.SendPropertyChanged("UA008");
					this.OnUA008Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UA009", DbType="VarChar(50)")]
		public string UA009
		{
			get
			{
				return this._UA009;
			}
			set
			{
				if ((this._UA009 != value))
				{
					this.OnUA009Changing(value);
					this.SendPropertyChanging();
					this._UA009 = value;
					this.SendPropertyChanged("UA009");
					this.OnUA009Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UA010", DbType="VarChar(50)")]
		public string UA010
		{
			get
			{
				return this._UA010;
			}
			set
			{
				if ((this._UA010 != value))
				{
					this.OnUA010Changing(value);
					this.SendPropertyChanging();
					this._UA010 = value;
					this.SendPropertyChanged("UA010");
					this.OnUA010Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UA011", DbType="DateTime")]
		public System.Nullable<System.DateTime> UA011
		{
			get
			{
				return this._UA011;
			}
			set
			{
				if ((this._UA011 != value))
				{
					this.OnUA011Changing(value);
					this.SendPropertyChanging();
					this._UA011 = value;
					this.SendPropertyChanged("UA011");
					this.OnUA011Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UA012", DbType="Bit")]
		public System.Nullable<bool> UA012
		{
			get
			{
				return this._UA012;
			}
			set
			{
				if ((this._UA012 != value))
				{
					this.OnUA012Changing(value);
					this.SendPropertyChanging();
					this._UA012 = value;
					this.SendPropertyChanged("UA012");
					this.OnUA012Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UA100", DbType="Bit")]
		public System.Nullable<bool> UA100
		{
			get
			{
				return this._UA100;
			}
			set
			{
				if ((this._UA100 != value))
				{
					this.OnUA100Changing(value);
					this.SendPropertyChanging();
					this._UA100 = value;
					this.SendPropertyChanged("UA100");
					this.OnUA100Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UA101", DbType="VarChar(100)")]
		public string UA101
		{
			get
			{
				return this._UA101;
			}
			set
			{
				if ((this._UA101 != value))
				{
					this.OnUA101Changing(value);
					this.SendPropertyChanging();
					this._UA101 = value;
					this.SendPropertyChanged("UA101");
					this.OnUA101Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="USEUA_USEUB", Storage="_USEUB", ThisKey="ID", OtherKey="UB001")]
		public EntitySet<USEUB> USEUB
		{
			get
			{
				return this._USEUB;
			}
			set
			{
				this._USEUB.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="USEUA_SYSLA", Storage="_SYSLA", ThisKey="ID", OtherKey="LA004")]
		public EntitySet<SYSLA> SYSLA
		{
			get
			{
				return this._SYSLA;
			}
			set
			{
				this._SYSLA.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="USEUA_SYSTB", Storage="_SYSTB", ThisKey="ID", OtherKey="TB001")]
		public EntitySet<SYSTB> SYSTB
		{
			get
			{
				return this._SYSTB;
			}
			set
			{
				this._SYSTB.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="USEUA_USERC", Storage="_USERC", ThisKey="ID", OtherKey="RC001")]
		public EntitySet<USERC> USERC
		{
			get
			{
				return this._USERC;
			}
			set
			{
				this._USERC.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_USEUB(USEUB entity)
		{
			this.SendPropertyChanging();
			entity.USEUA = this;
		}
		
		private void detach_USEUB(USEUB entity)
		{
			this.SendPropertyChanging();
			entity.USEUA = null;
		}
		
		private void attach_SYSLA(SYSLA entity)
		{
			this.SendPropertyChanging();
			entity.USEUA = this;
		}
		
		private void detach_SYSLA(SYSLA entity)
		{
			this.SendPropertyChanging();
			entity.USEUA = null;
		}
		
		private void attach_SYSTB(SYSTB entity)
		{
			this.SendPropertyChanging();
			entity.USEUA = this;
		}
		
		private void detach_SYSTB(SYSTB entity)
		{
			this.SendPropertyChanging();
			entity.USEUA = null;
		}
		
		private void attach_USERC(USERC entity)
		{
			this.SendPropertyChanging();
			entity.USEUA = this;
		}
		
		private void detach_USERC(USERC entity)
		{
			this.SendPropertyChanging();
			entity.USEUA = null;
		}
	}
}
#pragma warning restore 1591
